#Global configurations
global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.
scrape_configs:
  # - job_name: 'jaeger'
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ['jaeger:14269']  
  # - job_name: 'jaeger-ingester'
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ['jaeger-ingester:14270']  
  # - job_name: 'jaeger-query'
  #   metrics_path: '/metrics'
  #   static_configs:
  #     - targets: ['jaeger-query:16687']
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      # - targets: ['otel-collector:8888']  
  # - job_name: 'BookingTripService'
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: ['tripbooking:8080']  
  # - job_name: 'BookingCarService'
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: ['carbooking:8080']  
  # - job_name: 'BookingHotelService'
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: ['hotelbooking:8080']  
  # - job_name: 'BookingFlightService'
  #   metrics_path: '/actuator/prometheus'
  #   static_configs:
  #     - targets: ['flightbooking:8080']  