{
 "title": "Apache Camel with Spring Boot 3.x",
 "description": "Spring Boot Dashboard adapted from https://grafana.com/grafana/dashboards/10280-microservices-spring-boot-2-1/",
 "tags": [ "app" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": { "query": "label_values(application)" } },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", area=\"heap\"},id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{application=\"$application\", area=\"nonheap\"},id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_milliseconds{exported_job=\"$application\"} / 1000"
      }
     ]
    },
    {
     "title": "Heap Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{exported_job=\"$application\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{exported_job=\"$application\", area=\"heap\"})"
      }
     ]
    },
    {
     "title": "Non-Heap Used",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 11, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(jvm_memory_used_bytes{exported_job=\"$application\",  area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{exported_job=\"$application\",area=\"nonheap\"})"
      }
     ]
    },
    {
     "title": "Process Open Files",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "process_files_open{exported_job=\"$application\"}",
       "legendFormat": "Open Files"
      }
     ]
    },
    {
     "title": "Start time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_start_time_milliseconds{exported_job=\"$application\"}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_cpu_usage{exported_job=\"$application\"}",
       "legendFormat": "System CPU Usage"
      },
      {
       "expr": "process_cpu_usage{exported_job=\"$application\"}",
       "legendFormat": "Process CPU Usage"
      }
     ]
    },
    {
     "title": "Load Average",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "system_load_average_1m{exported_job=\"$application\"}",
       "legendFormat": "Load Average [1m]"
      },
      {
       "expr": "system_cpu_count{exported_job=\"$application\"}",
       "legendFormat": "CPU Core Size"
      }
     ]
    }
   ]
  },
  {
   "title": "Camel statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exchanges total rate",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 0, "y": 102 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(camel_exchanges_total{exported_job=\"$application\"}[1m]))"
      }
     ]
    },
    {
     "title": "Exchanges succeeded rate",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 6, "y": 102 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(camel_exchanges_succeeded_total{exported_job=\"$application\"}[1m]))"
      }
     ]
    },
    {
     "title": "Exchanges failed rate",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 12, "y": 102 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(camel_exchanges_failed_total{exported_job=\"$application\"}[1m]))"
      }
     ]
    },
    {
     "title": "Exchanges external redeliveries rate",
     "type": "stat",
     "gridPos": { "h": 2, "w": 6, "x": 18, "y": 102 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(camel_exchanges_external_redeliveries_total{exported_job=\"$application\"}[1m]))"
      }
     ]
    },
    {
     "title": "Average delay (CamelMessageHistory)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(camel_message_history_milliseconds_sum{exported_job=\"$application\"}[1m])/rate(camel_message_history_milliseconds_count{exported_job=\"$application\"}[1m])",
       "legendFormat": "{{nodeId}} [{{routeId}}]"
      }
     ]
    },
    {
     "title": "Average delay (CamelRoutePolicy)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 104 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(camel_message_history_milliseconds_sum{exported_job=\"$application\"}[1m])/rate(camel_message_history_milliseconds_count{exported_job=\"$application\"}[1m])",
       "legendFormat": "{{routeId}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "$memory_pool_heap (heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 90 },
     "repeat": "memory_pool_heap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{exported_job=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{exported_job=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{ exported_job=\"$application\", id=\"$memory_pool_heap\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "$memory_pool_nonheap (non-heap)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
     "repeat": "memory_pool_nonheap",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{exported_job=\"$application\", id=\"${memory_pool_nonheap:raw}\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "jvm_memory_committed_bytes{exported_job=\"$application\", id=\"${memory_pool_nonheap:raw}\"}",
       "legendFormat": "Commited"
      },
      {
       "expr": "jvm_memory_max_bytes{exported_job=\"$application\", id=\"${memory_pool_nonheap:raw}\"}",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Direct Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{exported_job=\"$application\", id=\"direct\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{exported_job=\"$application\", id=\"direct\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_threads_daemon{exported_job=\"$application\"}",
       "legendFormat": "Daemon"
      },
      {
       "expr": "jvm_threads_live{exported_job=\"$application\"}",
       "legendFormat": "Live"
      },
      {
       "expr": "jvm_threads_peak{exported_job=\"$application\"}",
       "legendFormat": "Peak"
      }
     ]
    },
    {
     "title": "Memory Allocate/Promote",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_memory_allocated_bytes_total{exported_job=\"$application\"}[$__rate_interval])",
       "legendFormat": "allocated"
      },
      {
       "expr": "irate(jvm_gc_memory_promoted_bytes_total{exported_job=\"$application\"}[$__rate_interval])",
       "legendFormat": "promoted"
      }
     ]
    },
    {
     "title": "Mapped Buffers",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{exported_job=\"$application\", id=\"mapped\"}",
       "legendFormat": "Used Bytes"
      },
      {
       "expr": "jvm_buffer_total_capacity_bytes{exported_job=\"$application\", id=\"mapped\"}",
       "legendFormat": "Capacity Bytes"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_milliseconds_count{exported_job=\"$application\"}[$__rate_interval])",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    },
    {
     "title": "GC Stop the World Duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(jvm_gc_pause_milliseconds_sum{exported_job=\"$application\"}[$__rate_interval]) / 1000",
       "legendFormat": "{{action}} [{{cause}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Request Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_milliseconds_count{exported_job=\"$application\", uri!~\".*(prometheus|health).*\"}[$__rate_interval])",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    },
    {
     "title": "Response Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "irate(http_server_requests_milliseconds_sum{exported_job=\"$application\", exception=\"none\", uri!~\".*(prometheus|health).*\"}[$__rate_interval]) / irate(http_server_requests_milliseconds_count{exported_job=\"$application\", exception=\"none\",uri!~\".*(prometheus|health).*\"}[$__rate_interval]) / 1000",
       "legendFormat": "{{method}} [{{status}}] - {{uri}}"
      }
     ]
    }
   ]
  },
  { "title": "Kafka Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Kafka Consumer Lag (per topic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(kafka_consumer_records_lag{exported_job=~\"$application\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Fetch Latency Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "avg(kafka_consumer_fetch_latency_avg{exported_job=~\"$application\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Kafka Producer Request Latency Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg(kafka_producer_request_latency_avg{exported_job=~\"$application\"}) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Kafka Producer Bytes Rate (per topic)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(kafka_producer_byte_rate{exported_job=~\"$application\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "INFO logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{exported_job=\"$application\", level=\"info\"}[$__rate_interval])",
       "legendFormat": "info",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "ERROR logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{exported_job=\"$application\", level=\"error\"}[$__rate_interval])",
       "legendFormat": "error",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "WARN logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{exported_job=\"$application\", level=\"warn\"}[$__rate_interval])",
       "legendFormat": "warn",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "DEBUG logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{exported_job=\"$application\", level=\"debug\"}[$__rate_interval])",
       "legendFormat": "debug",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    },
    {
     "title": "TRACE logs",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(logback_events_total{exported_job=\"$application\", level=\"trace\"}[$__rate_interval])",
       "legendFormat": "trace",
       "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
      }
     ]
    }
   ]
  }
 ]
}