# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Building apps

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build TripBooking app
      run: mvn -B package --file TripBooking/pom.xml
    
    - name: Build FlightBooking app
      run: mvn -B package --file FlightBooking/pom.xml
      
    - name: Build HotelBooking app
      run: mvn -B package --file HotelBooking/pom.xml
      
    - name: Build CarBooking app
      run: mvn -B package --file CarBooking/pom.xml
